from enum import StrEnum


class TaskStatus(StrEnum):
    PENDING = "pending"
    QUEUED = "queued"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class TaskErrorCode(StrEnum):
    UNKNOWN = "UNKNOWN"
    TIMEOUT = "TIMEOUT"
    CANCELLED = "CANCELLED"
    LLM_UNAVAILABLE = "LLM_UNAVAILABLE"
    LLM_RATE_LIMITED = "LLM_RATE_LIMITED"
    LLM_RESPONSE_INVALID = "LLM_RESPONSE_INVALID"
    MANIM_CODE_GENERATION_FAILED = "MANIM_CODE_GENERATION_FAILED"
    MANIM_RENDER_FAILED = "MANIM_RENDER_FAILED"
    MANIM_SANDBOX_ERROR = "MANIM_SANDBOX_ERROR"
    TTS_SYNTHESIS_FAILED = "TTS_SYNTHESIS_FAILED"
    TTS_ALL_PROVIDERS_FAILED = "TTS_ALL_PROVIDERS_FAILED"
    EXTERNAL_SERVICE_UNAVAILABLE = "EXTERNAL_SERVICE_UNAVAILABLE"
    EXTERNAL_SERVICE_TIMEOUT = "EXTERNAL_SERVICE_TIMEOUT"
    COS_UPLOAD_FAILED = "COS_UPLOAD_FAILED"
