/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Link: typeof import('react-router-dom').Link
  const NavLink: typeof import('react-router-dom').NavLink
  const Outlet: typeof import('react-router-dom').Outlet
  const useEffect: typeof import('react').useEffect
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useMutation: typeof import('@tanstack/react-query').useMutation
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useParams: typeof import('react-router-dom').useParams
  const useQuery: typeof import('@tanstack/react-query').useQuery
  const useQueryClient: typeof import('@tanstack/react-query').useQueryClient
  const useRef: typeof import('react').useRef
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useState: typeof import('react').useState
  const useTransition: typeof import('react').useTransition
}
