name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # 变更内容

  $CHANGES

  **完整变更日志**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '破坏性变更'
    label: 'breaking-change'
  - title: '新功能'
    label: 'new-feature'
  - title: 'Bug 修复'
    label: 'bugfix'
  - title: '维护更新'
    label: 'maintenance'
  - title: '文档更新'
    label: 'documentation'
  - title: '性能优化'
    label: 'performance'
  - title: '重构'
    label: 'refactor'
  - title: 'CI / 工作流'
    label: 'ci'
  - title: '其他变更'
  - title: '依赖更新'
    label: 'dependencies'
    collapse-after: 5

version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'new-feature'
  patch:
    labels:
      - 'bugfix'
      - 'maintenance'
      - 'documentation'
      - 'dependencies'
      - 'ci'
      - 'refactor'
      - 'performance'
      - 'security'

exclude-labels:
  - 'skip-changelog'
