-- Epic 10 Story 10.1
-- 长期业务数据边界、业务表清单与字段基线冻结

CREATE TABLE IF NOT EXISTS xm_video_task (
    id bigint NOT NULL COMMENT '主键',
    tenant_id varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户编号',
    task_id varchar(64) NOT NULL COMMENT '视频任务业务 ID',
    user_id bigint NOT NULL COMMENT '用户 ID',
    task_type varchar(32) NOT NULL DEFAULT 'video' COMMENT '任务类型',
    source_type varchar(32) NOT NULL COMMENT '来源类型',
    title varchar(255) DEFAULT NULL COMMENT '标题',
    status varchar(32) NOT NULL COMMENT '任务状态',
    summary varchar(1000) DEFAULT NULL COMMENT '结果摘要',
    detail_ref_type varchar(64) DEFAULT NULL COMMENT '详情定位类型',
    detail_ref_id varchar(64) DEFAULT NULL COMMENT '详情定位 ID',
    result_object_key varchar(512) DEFAULT NULL COMMENT '结果对象引用',
    artifact_session_id varchar(64) DEFAULT NULL COMMENT '产物图关联键',
    failure_code varchar(64) DEFAULT NULL COMMENT '失败错误码',
    failure_summary varchar(1000) DEFAULT NULL COMMENT '失败摘要',
    started_at datetime DEFAULT NULL COMMENT '开始时间',
    completed_at datetime DEFAULT NULL COMMENT '完成时间',
    failed_at datetime DEFAULT NULL COMMENT '失败时间',
    create_dept bigint DEFAULT NULL COMMENT '创建部门',
    create_by bigint DEFAULT NULL COMMENT '创建者',
    create_time datetime DEFAULT NULL COMMENT '创建时间',
    update_by bigint DEFAULT NULL COMMENT '更新者',
    update_time datetime DEFAULT NULL COMMENT '更新时间',
    del_flag char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
    PRIMARY KEY (id),
    UNIQUE KEY uk_xm_video_task_task_id (task_id),
    KEY idx_xm_video_task_user_status (tenant_id, user_id, status),
    KEY idx_xm_video_task_completed_at (tenant_id, completed_at)
) ENGINE=InnoDB COMMENT='视频任务长期元数据';

CREATE TABLE IF NOT EXISTS xm_classroom_session (
    id bigint NOT NULL COMMENT '主键',
    tenant_id varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户编号',
    session_id varchar(64) NOT NULL COMMENT '课堂会话业务 ID',
    user_id bigint NOT NULL COMMENT '用户 ID',
    topic varchar(255) DEFAULT NULL COMMENT '课堂主题',
    status varchar(32) NOT NULL COMMENT '会话状态',
    summary varchar(1000) DEFAULT NULL COMMENT '会话摘要',
    detail_ref_type varchar(64) DEFAULT NULL COMMENT '详情定位类型',
    detail_ref_id varchar(64) DEFAULT NULL COMMENT '详情定位 ID',
    artifact_session_id varchar(64) DEFAULT NULL COMMENT '产物图关联键',
    slide_count int DEFAULT 0 COMMENT '幻灯片数量',
    completion_signal varchar(64) DEFAULT NULL COMMENT '完成信号',
    failure_code varchar(64) DEFAULT NULL COMMENT '失败错误码',
    failure_summary varchar(1000) DEFAULT NULL COMMENT '失败摘要',
    started_at datetime DEFAULT NULL COMMENT '开始时间',
    completed_at datetime DEFAULT NULL COMMENT '完成时间',
    failed_at datetime DEFAULT NULL COMMENT '失败时间',
    create_dept bigint DEFAULT NULL COMMENT '创建部门',
    create_by bigint DEFAULT NULL COMMENT '创建者',
    create_time datetime DEFAULT NULL COMMENT '创建时间',
    update_by bigint DEFAULT NULL COMMENT '更新者',
    update_time datetime DEFAULT NULL COMMENT '更新时间',
    del_flag char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
    PRIMARY KEY (id),
    UNIQUE KEY uk_xm_classroom_session_session_id (session_id),
    KEY idx_xm_classroom_session_user_status (tenant_id, user_id, status),
    KEY idx_xm_classroom_session_completed_at (tenant_id, completed_at)
) ENGINE=InnoDB COMMENT='课堂会话长期摘要';

CREATE TABLE IF NOT EXISTS xm_session_artifact (
    id bigint NOT NULL COMMENT '主键',
    tenant_id varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户编号',
    session_type varchar(32) NOT NULL COMMENT '会话类型',
    session_ref_id varchar(64) NOT NULL COMMENT '会话关联 ID',
    artifact_type varchar(64) NOT NULL COMMENT '产物类型',
    anchor_type varchar(64) DEFAULT NULL COMMENT '锚点类型',
    anchor_key varchar(128) DEFAULT NULL COMMENT '锚点标识',
    sequence_no int NOT NULL DEFAULT 0 COMMENT '顺序号',
    title varchar(255) DEFAULT NULL COMMENT '产物标题',
    summary varchar(1000) DEFAULT NULL COMMENT '产物摘要',
    object_key varchar(512) DEFAULT NULL COMMENT '对象引用',
    payload_ref varchar(512) DEFAULT NULL COMMENT '详情载荷引用',
    metadata_json json DEFAULT NULL COMMENT '结构化元数据',
    occurred_at datetime DEFAULT NULL COMMENT '产物时间',
    create_dept bigint DEFAULT NULL COMMENT '创建部门',
    create_by bigint DEFAULT NULL COMMENT '创建者',
    create_time datetime DEFAULT NULL COMMENT '创建时间',
    update_by bigint DEFAULT NULL COMMENT '更新者',
    update_time datetime DEFAULT NULL COMMENT '更新时间',
    del_flag char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
    PRIMARY KEY (id),
    KEY idx_xm_session_artifact_session (tenant_id, session_type, session_ref_id),
    KEY idx_xm_session_artifact_anchor (tenant_id, anchor_type, anchor_key)
) ENGINE=InnoDB COMMENT='SessionArtifactGraph 长期索引';

CREATE TABLE IF NOT EXISTS xm_companion_turn (
    id bigint NOT NULL COMMENT '主键',
    tenant_id varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户编号',
    turn_id varchar(64) NOT NULL COMMENT '问答轮次业务 ID',
    session_type varchar(32) NOT NULL COMMENT '会话类型',
    session_ref_id varchar(64) NOT NULL COMMENT '会话关联 ID',
    user_id bigint NOT NULL COMMENT '用户 ID',
    anchor_type varchar(64) DEFAULT NULL COMMENT '锚点类型',
    anchor_key varchar(128) DEFAULT NULL COMMENT '锚点标识',
    question_text text COMMENT '提问正文',
    answer_summary text COMMENT '回答摘要',
    source_summary varchar(1000) DEFAULT NULL COMMENT '来源摘要',
    source_ref_count int NOT NULL DEFAULT 0 COMMENT '来源数量',
    whiteboard_status varchar(32) DEFAULT NULL COMMENT '白板状态',
    turn_status varchar(32) NOT NULL COMMENT '轮次状态',
    followup_count int NOT NULL DEFAULT 0 COMMENT '追问数量',
    occurred_at datetime DEFAULT NULL COMMENT '发生时间',
    create_dept bigint DEFAULT NULL COMMENT '创建部门',
    create_by bigint DEFAULT NULL COMMENT '创建者',
    create_time datetime DEFAULT NULL COMMENT '创建时间',
    update_by bigint DEFAULT NULL COMMENT '更新者',
    update_time datetime DEFAULT NULL COMMENT '更新时间',
    del_flag char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
    PRIMARY KEY (id),
    UNIQUE KEY uk_xm_companion_turn_turn_id (turn_id),
    KEY idx_xm_companion_turn_session (tenant_id, session_type, session_ref_id),
    KEY idx_xm_companion_turn_user_time (tenant_id, user_id, occurred_at)
) ENGINE=InnoDB COMMENT='Companion 问答主记录';

CREATE TABLE IF NOT EXISTS xm_whiteboard_action_log (
    id bigint NOT NULL COMMENT '主键',
    tenant_id varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户编号',
    turn_id varchar(64) NOT NULL COMMENT '关联 turn ID',
    session_type varchar(32) NOT NULL COMMENT '会话类型',
    session_ref_id varchar(64) NOT NULL COMMENT '会话关联 ID',
    action_type varchar(64) NOT NULL COMMENT '动作类型',
    sequence_no int NOT NULL DEFAULT 0 COMMENT '顺序号',
    action_status varchar(32) NOT NULL COMMENT '动作状态',
    action_payload_json json DEFAULT NULL COMMENT '结构化动作内容',
    render_object_key varchar(512) DEFAULT NULL COMMENT '渲染对象引用',
    degraded_reason varchar(255) DEFAULT NULL COMMENT '降级原因',
    occurred_at datetime DEFAULT NULL COMMENT '发生时间',
    create_dept bigint DEFAULT NULL COMMENT '创建部门',
    create_by bigint DEFAULT NULL COMMENT '创建者',
    create_time datetime DEFAULT NULL COMMENT '创建时间',
    update_by bigint DEFAULT NULL COMMENT '更新者',
    update_time datetime DEFAULT NULL COMMENT '更新时间',
    del_flag char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
    PRIMARY KEY (id),
    KEY idx_xm_whiteboard_action_turn (tenant_id, turn_id, sequence_no),
    KEY idx_xm_whiteboard_action_session (tenant_id, session_type, session_ref_id)
) ENGINE=InnoDB COMMENT='白板动作日志';

CREATE TABLE IF NOT EXISTS xm_knowledge_chat_log (
    id bigint NOT NULL COMMENT '主键',
    tenant_id varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户编号',
    chat_id varchar(64) NOT NULL COMMENT '问答业务 ID',
    session_scope_type varchar(32) NOT NULL COMMENT '范围类型',
    session_ref_id varchar(64) DEFAULT NULL COMMENT '会话或结果关联 ID',
    user_id bigint NOT NULL COMMENT '用户 ID',
    range_type varchar(64) DEFAULT NULL COMMENT '检索范围类型',
    range_key varchar(128) DEFAULT NULL COMMENT '检索范围标识',
    question_text text COMMENT '提问正文',
    answer_summary text COMMENT '回答摘要',
    citation_payload_json json DEFAULT NULL COMMENT '引用来源载荷',
    source_summary varchar(1000) DEFAULT NULL COMMENT '来源摘要',
    chat_status varchar(32) NOT NULL COMMENT '问答状态',
    occurred_at datetime DEFAULT NULL COMMENT '发生时间',
    create_dept bigint DEFAULT NULL COMMENT '创建部门',
    create_by bigint DEFAULT NULL COMMENT '创建者',
    create_time datetime DEFAULT NULL COMMENT '创建时间',
    update_by bigint DEFAULT NULL COMMENT '更新者',
    update_time datetime DEFAULT NULL COMMENT '更新时间',
    del_flag char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
    PRIMARY KEY (id),
    UNIQUE KEY uk_xm_knowledge_chat_log_chat_id (chat_id),
    KEY idx_xm_knowledge_chat_log_scope (tenant_id, session_scope_type, session_ref_id),
    KEY idx_xm_knowledge_chat_log_user_time (tenant_id, user_id, occurred_at)
) ENGINE=InnoDB COMMENT='Evidence / Retrieval 问答历史';

CREATE TABLE IF NOT EXISTS xm_quiz_result (
    id bigint NOT NULL COMMENT '主键',
    tenant_id varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户编号',
    result_id varchar(64) NOT NULL COMMENT '结果业务 ID',
    user_id bigint NOT NULL COMMENT '用户 ID',
    result_type varchar(32) NOT NULL COMMENT '结果类型',
    source_session_type varchar(32) DEFAULT NULL COMMENT '来源会话类型',
    source_session_id varchar(64) DEFAULT NULL COMMENT '来源会话 ID',
    source_result_id varchar(64) DEFAULT NULL COMMENT '来源结果 ID',
    title varchar(255) DEFAULT NULL COMMENT '结果标题',
    score decimal(5,2) DEFAULT NULL COMMENT '得分',
    max_score decimal(5,2) DEFAULT NULL COMMENT '满分',
    status varchar(32) NOT NULL COMMENT '结果状态',
    analysis_summary text COMMENT '解析摘要',
    detail_payload_json json DEFAULT NULL COMMENT '结构化详情',
    detail_ref_type varchar(64) DEFAULT NULL COMMENT '详情定位类型',
    detail_ref_id varchar(64) DEFAULT NULL COMMENT '详情定位 ID',
    generated_at datetime DEFAULT NULL COMMENT '生成时间',
    completed_at datetime DEFAULT NULL COMMENT '完成时间',
    create_dept bigint DEFAULT NULL COMMENT '创建部门',
    create_by bigint DEFAULT NULL COMMENT '创建者',
    create_time datetime DEFAULT NULL COMMENT '创建时间',
    update_by bigint DEFAULT NULL COMMENT '更新者',
    update_time datetime DEFAULT NULL COMMENT '更新时间',
    del_flag char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
    PRIMARY KEY (id),
    UNIQUE KEY uk_xm_quiz_result_result_id (result_id),
    KEY idx_xm_quiz_result_user_type (tenant_id, user_id, result_type),
    KEY idx_xm_quiz_result_source_result (tenant_id, source_result_id)
) ENGINE=InnoDB COMMENT='Learning Coach 结果主表';

CREATE TABLE IF NOT EXISTS xm_learning_path (
    id bigint NOT NULL COMMENT '主键',
    tenant_id varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户编号',
    path_id varchar(64) NOT NULL COMMENT '路径业务 ID',
    user_id bigint NOT NULL COMMENT '用户 ID',
    source_session_id varchar(64) DEFAULT NULL COMMENT '来源会话 ID',
    source_result_id varchar(64) DEFAULT NULL COMMENT '来源结果 ID',
    version_no int NOT NULL DEFAULT 1 COMMENT '版本号',
    status varchar(32) NOT NULL COMMENT '路径状态',
    title varchar(255) DEFAULT NULL COMMENT '路径标题',
    summary text COMMENT '路径摘要',
    node_count int NOT NULL DEFAULT 0 COMMENT '节点数',
    detail_payload_json json DEFAULT NULL COMMENT '结构化路径详情',
    published_at datetime DEFAULT NULL COMMENT '发布时间',
    updated_snapshot_at datetime DEFAULT NULL COMMENT '最近更新时间',
    create_dept bigint DEFAULT NULL COMMENT '创建部门',
    create_by bigint DEFAULT NULL COMMENT '创建者',
    create_time datetime DEFAULT NULL COMMENT '创建时间',
    update_by bigint DEFAULT NULL COMMENT '更新者',
    update_time datetime DEFAULT NULL COMMENT '更新时间',
    del_flag char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
    PRIMARY KEY (id),
    UNIQUE KEY uk_xm_learning_path_path_id (path_id),
    KEY idx_xm_learning_path_user_status (tenant_id, user_id, status),
    KEY idx_xm_learning_path_source_result (tenant_id, source_result_id)
) ENGINE=InnoDB COMMENT='学习路径长期承接';

CREATE TABLE IF NOT EXISTS xm_learning_record (
    id bigint NOT NULL COMMENT '主键',
    tenant_id varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户编号',
    record_id varchar(64) NOT NULL COMMENT '记录业务 ID',
    user_id bigint NOT NULL COMMENT '用户 ID',
    record_type varchar(32) NOT NULL COMMENT '记录类型',
    source_table varchar(64) NOT NULL COMMENT '来源表',
    source_id varchar(64) NOT NULL COMMENT '来源 ID',
    source_session_id varchar(64) DEFAULT NULL COMMENT '来源会话 ID',
    source_title varchar(255) DEFAULT NULL COMMENT '展示标题',
    summary varchar(1000) DEFAULT NULL COMMENT '摘要',
    status varchar(32) NOT NULL COMMENT '记录状态',
    detail_route varchar(255) DEFAULT NULL COMMENT '详情路由',
    is_favorite char(1) NOT NULL DEFAULT 'N' COMMENT '是否收藏',
    last_accessed_at datetime DEFAULT NULL COMMENT '最近访问时间',
    occurred_at datetime DEFAULT NULL COMMENT '发生时间',
    create_dept bigint DEFAULT NULL COMMENT '创建部门',
    create_by bigint DEFAULT NULL COMMENT '创建者',
    create_time datetime DEFAULT NULL COMMENT '创建时间',
    update_by bigint DEFAULT NULL COMMENT '更新者',
    update_time datetime DEFAULT NULL COMMENT '更新时间',
    del_flag char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
    PRIMARY KEY (id),
    UNIQUE KEY uk_xm_learning_record_record_id (record_id),
    KEY idx_xm_learning_record_user_type (tenant_id, user_id, record_type),
    KEY idx_xm_learning_record_source (tenant_id, source_table, source_id),
    KEY idx_xm_learning_record_occurred_at (tenant_id, occurred_at)
) ENGINE=InnoDB COMMENT='学习中心历史索引';

CREATE TABLE IF NOT EXISTS xm_learning_favorite (
    id bigint NOT NULL COMMENT '主键',
    tenant_id varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户编号',
    favorite_id varchar(64) NOT NULL COMMENT '收藏业务 ID',
    user_id bigint NOT NULL COMMENT '用户 ID',
    record_id varchar(64) NOT NULL COMMENT '学习记录 ID',
    source_table varchar(64) NOT NULL COMMENT '来源表',
    source_id varchar(64) NOT NULL COMMENT '来源 ID',
    record_type varchar(32) NOT NULL COMMENT '记录类型',
    title varchar(255) DEFAULT NULL COMMENT '收藏标题',
    summary varchar(1000) DEFAULT NULL COMMENT '收藏摘要',
    status varchar(32) NOT NULL COMMENT '收藏状态',
    favorited_at datetime DEFAULT NULL COMMENT '收藏时间',
    removed_at datetime DEFAULT NULL COMMENT '取消收藏时间',
    create_dept bigint DEFAULT NULL COMMENT '创建部门',
    create_by bigint DEFAULT NULL COMMENT '创建者',
    create_time datetime DEFAULT NULL COMMENT '创建时间',
    update_by bigint DEFAULT NULL COMMENT '更新者',
    update_time datetime DEFAULT NULL COMMENT '更新时间',
    del_flag char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
    PRIMARY KEY (id),
    UNIQUE KEY uk_xm_learning_favorite_favorite_id (favorite_id),
    KEY idx_xm_learning_favorite_user_status (tenant_id, user_id, status),
    KEY idx_xm_learning_favorite_record (tenant_id, record_id)
) ENGINE=InnoDB COMMENT='学习中心收藏记录';
